version: 2

defaults: &defaults
  docker:
    - image: circleci/node:7.10

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  test:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Unit-Test
          command: yarn test

      - run:
          name: Mutation-Test
          command: node_modules/.bin/stryker run

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: /^master$/
